# Generated by Django 6.1.1 on 2026-09-15 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('concluido', models.BooleanField(default=True)),
                ('data_emissao', models.DateField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='usuarios.usuario')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='cursos.curso')),
            ],
        ),
    ]
